### ISSUE TITLE
Credits Required

### ISSUE THREAD

**Issue by proudparrot2** [UseRaptor-Proxy/Raptor-Proxy#15]
Hey there, [Interstellar](https://github.com/useinterstellar/interstellar) legal rep here 👋

Interesting project... however, this is a violation of our open source license ([AGPL-3.0](https://github.com/UseInterstellar/Interstellar/blob/main/LICENSE)), since you aren't showing that Interstellar is the original source of your repository.

Our devs worked very hard on this and it's a shame to see it used like this. Please respond with credit attributed in your README (or other location in the repository) and respond back to us, or we'll have to pursue DMCA's with GitHub. Thanks!

**Comment by Globalfun32y439y54** [comment]
Done
